# Generated by Django 5.2.5 on 2025-08-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='estimated_cost',
            field=models.IntegerField(default=0),
        ),
    ]
