# Generated by Django 5.2.5 on 2025-08-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='service_type',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='estimated_cost',
            field=models.FloatField(default=0),
        ),
    ]
