# Generated by Django 5.2.5 on 2025-09-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_servicerequest_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.serviceprovider'),
        ),
    ]
