# Generated by Django 5.2.5 on 2025-09-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_servicerequest_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
