# Generated by Django 5.2.5 on 2025-09-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serviceprovider_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='phone',
            field=models.CharField(max_length=32),
        ),
    ]
