# Generated by Django 5.2.5 on 2025-09-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_servicerequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(default='provider@gmail.com', max_length=254),
        ),
    ]
