# Generated by Django 5.2.5 on 2025-09-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_serviceprovider_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='arrived_by_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='arrived_by_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_by_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='completed_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
